name: vtm_assistant
description: Unofficial assistant for role play game "Vampire the Masquerade" revised edition.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.4.0
  flutter_riverpod: ^2.3.6
  sqflite: ^2.2.8+4
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3
  freezed: ^2.3.5
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/db/
    - assets/images/clan_logos/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
